# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x07\n\x05\x45mpty\"e\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0bnama_produk\x18\x02 \x01(\t\x12\x14\n\x0charga_produk\x18\x03 \x01(\x02\x12\x15\n\rdetail_produk\x18\x04 \x01(\t\x12\x0c\n\x04stok\x18\x05 \x01(\x05\"1\n\x0bProductList\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\"`\n\x0eProductRequest\x12\x13\n\x0bnama_produk\x18\x01 \x01(\t\x12\x14\n\x0charga_produk\x18\x02 \x01(\x02\x12\x15\n\rdetail_produk\x18\x03 \x01(\t\x12\x0c\n\x04stok\x18\x04 \x01(\x05\"@\n\x0fProductResponse\x12\r\n\x05greet\x18\x01 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x10.product.Product\"\x17\n\tProductId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x8f\x03\n\x0eProductService\x12\x36\n\x0eGetProductList\x12\x0e.product.Empty\x1a\x14.product.ProductList\x12\x42\n\rCreateProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12?\n\rUpdateProduct\x12\x14.product.ProductList\x1a\x18.product.ProductResponse\x12=\n\rDeleteProduct\x12\x12.product.ProductId\x1a\x18.product.ProductResponse\x12>\n\x0eGetProductById\x12\x12.product.ProductId\x1a\x18.product.ProductResponse\x12\x41\n\x0fGetProductCount\x12\x14.product.ProductList\x1a\x18.product.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PRODUCT']._serialized_start=35
  _globals['_PRODUCT']._serialized_end=136
  _globals['_PRODUCTLIST']._serialized_start=138
  _globals['_PRODUCTLIST']._serialized_end=187
  _globals['_PRODUCTREQUEST']._serialized_start=189
  _globals['_PRODUCTREQUEST']._serialized_end=285
  _globals['_PRODUCTRESPONSE']._serialized_start=287
  _globals['_PRODUCTRESPONSE']._serialized_end=351
  _globals['_PRODUCTID']._serialized_start=353
  _globals['_PRODUCTID']._serialized_end=376
  _globals['_PRODUCTSERVICE']._serialized_start=379
  _globals['_PRODUCTSERVICE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
