run develop:
	@echo "Running development server"
	venv\Scripts\pserve ini\development.ini --reload

install develop:
	@echo "Installing dependencies, if error occurs, cd into server\ini then run make install develop"
	venv\Scripts\pip install -e ".[dev]"